/**
 * zxingReader.ts — the symbol reader behind `qrDecode.ts`'s ladder.
 *
 * zxing-cpp, compiled to WebAssembly, with the binary **inlined into the bundle
 * as base64 source** (`vendor/zxingReaderWasm.ts`, generated by
 * `scripts/vendor-zxing.mjs`).
 *
 * ## Why inlined rather than an asset
 *
 * The CONSUME contract is self-contained: nothing is fetched at runtime, from
 * anywhere, **including the app's own origin**. A student on a train with no
 * signal must be able to finish. WebAssembly is not forbidden; *fetching* is.
 *
 * Two defaults have to be defeated for that to be true, and neither is obvious:
 * `zxing-wasm`'s published `locateFile` points at `fastly.jsdelivr.net`, and
 * Vite would emit `zxing_reader.wasm` as a separate same-origin asset that the
 * emscripten glue fetches on first use. Handing emscripten `wasmBinary`
 * directly defeats both — there is no `fetch` on any path, not even of a
 * `data:` URI, and no window in which the app is up and the decoder is not.
 *
 * ## Why the read is synchronous
 *
 * The package's `readBarcodes` is `async`, and taking that at face value makes
 * `decodePageQrCandidates`, `registerPage` and `runCaptureGate` async too — a
 * change to the shape of three modules and their tests for no functional gain.
 * The promise exists only because the module may still need building, so the
 * build is hoisted into `initQrReader()` and the read itself is an ordinary
 * synchronous call.
 *
 * The cost is that this reaches past the public API: `_malloc`, `HEAPU8` and
 * `readBarcodesFromPixmap` are marked `@internal` by the package, as is the
 * option encoding reproduced in `encodeOptions` below. They are stable across
 * the emscripten binding, but it is a coupling — which is why `zxing-wasm` is
 * pinned to an exact version with no caret, and why the version and the SHA-256
 * of the binary are asserted in `tests/qr-decoder-tests.mjs`.
 */

import {
  prepareZXingModule,
  binarizers,
  characterSets,
  eanAddOnSymbols,
  textModes,
  type ReaderOptions,
} from 'zxing-wasm/reader';
import { ZXING_READER_WASM_BASE64 } from '../vendor/zxingReaderWasm';
import { Rgba } from './raster';
import { Point } from './homography';

export interface RawSymbol {
  text: string;
  corners: { topLeft: Point; topRight: Point; bottomRight: Point; bottomLeft: Point };
}

/**
 * The three emscripten members the synchronous path needs, named here rather
 * than imported: the package types them through `EmscriptenModule`, which comes
 * from `@types/emscripten` and is not a dependency of this app. Declaring the
 * shape locally keeps the coupling visible and in one place — it is the same
 * `@internal` surface the module comment warns about.
 */
interface ZXingPixmapReader {
  _malloc(size: number): number;
  _free(ptr: number): void;
  HEAPU8: Uint8Array;
  readBarcodesFromPixmap(
    bufferPtr: number, width: number, height: number, options: unknown,
  ): {
    size(): number;
    get(i: number): {
      isValid: boolean;
      text: string;
      position: {
        topLeft: Point; topRight: Point; bottomRight: Point; bottomLeft: Point;
      };
    } | undefined;
  };
}

/**
 * Reader options.
 *
 * `formats: ['QRCode']` is the whole of the tuning. Everything else is the
 * library default, and the defaults matter: measured on the 2026-09-01
 * evaluation, turning `tryHarder` / `tryRotate` / `tryInvert` / `tryDownscale`
 * off drops the repo's 29-capture set from 28 reads to 14. There is no cheap
 * mode here worth having.
 *
 * **`tryDenoise` is on and is the one non-default.** It is marked
 * `@experimental` by the library — "may change without a major version bump" —
 * and it is the only setting that reads `stale04`, a capture that passes today.
 * It is not needed by the 2026-09-07 corpus, which reads 12 of 12 either way;
 * it is needed by the existing suite, which is the tripwire if a version bump
 * ever removes it.
 */
const READER_OPTIONS: ReaderOptions = {
  formats: ['QRCode'],
  tryDenoise: true,
};

/**
 * The `@internal` encoding `readBarcodesFromPixmap` expects, reproduced from the
 * package's own exported tables rather than guessed. `readerOptionsToZXingReaderOptions`
 * is not exported from the reader entry point, but every table it indexes into is.
 */
const encodeOptions = (options: ReaderOptions) => ({
  formats: (options.formats ?? []).join(','),
  tryHarder: options.tryHarder ?? true,
  tryRotate: options.tryRotate ?? true,
  tryInvert: options.tryInvert ?? true,
  tryDownscale: options.tryDownscale ?? true,
  tryDenoise: options.tryDenoise ?? false,
  binarizer: binarizers.indexOf(options.binarizer ?? 'LocalAverage'),
  isPure: options.isPure ?? false,
  downscaleFactor: options.downscaleFactor ?? 3,
  downscaleThreshold: options.downscaleThreshold ?? 500,
  minLineCount: options.minLineCount ?? 2,
  maxNumberOfSymbols: options.maxNumberOfSymbols ?? 255,
  validateOptionalChecksum: options.validateOptionalChecksum ?? false,
  returnErrors: options.returnErrors ?? false,
  eanAddOnSymbol: eanAddOnSymbols.indexOf(options.eanAddOnSymbol ?? 'Ignore'),
  textMode: textModes.indexOf(options.textMode ?? 'HRI'),
  characterSet: characterSets.indexOf(options.characterSet ?? 'Unknown'),
  tryCode39ExtendedMode: true,
});

const ENCODED_OPTIONS = encodeOptions(READER_OPTIONS);

const decodeBase64 = (text: string): Uint8Array => {
  const binary = atob(text);
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);
  return out;
};

let modulePromise: Promise<ZXingPixmapReader> | null = null;
let readyModule: ZXingPixmapReader | null = null;

/**
 * Build the decoder. Idempotent, and cheap after the first call.
 *
 * Compiling and instantiating a 1.07 MB binary is a few milliseconds on a
 * desktop and tens on a phone; there is nothing to fetch, so this cannot fail
 * on a bad connection. Every caller of `decodePageQrCandidates` must have
 * awaited this — `registerAndCropPage` does, and the app also starts it early
 * so the cost is paid before the student has taken a photograph.
 */
export const initQrReader = async (): Promise<void> => {
  if (readyModule) return;
  if (!modulePromise) {
    const wasmBinary = decodeBase64(ZXING_READER_WASM_BASE64);
    modulePromise = prepareZXingModule({
      overrides: {
        wasmBinary: wasmBinary.buffer.slice(
          wasmBinary.byteOffset, wasmBinary.byteOffset + wasmBinary.byteLength,
        ) as ArrayBuffer,
      },
      fireImmediately: true,
    }) as unknown as Promise<ZXingPixmapReader>;
  }
  readyModule = await modulePromise;
};

/** True once `initQrReader` has resolved. */
export const qrReaderReady = (): boolean => readyModule !== null;

/** RGBA to the one-byte-per-pixel luma the pixmap entry point takes. */
const toGrayscale = (image: Rgba): Uint8Array => {
  const count = image.width * image.height;
  const gray = new Uint8Array(count);
  const data = image.data;
  for (let i = 0; i < count; i++) {
    const p = i << 2;
    gray[i] = (306 * data[p] + 601 * data[p + 1] + 117 * data[p + 2] + 512) >> 10;
  }
  return gray;
};

/**
 * Every QR symbol in this raster, in the raster's own pixel frame.
 *
 * Returns `[]` rather than throwing when the module is not built: a decoder
 * that is not ready is indistinguishable, to the student, from a photograph
 * that did not read, and the recovery is the same.
 */
export const readSymbols = (image: Rgba): RawSymbol[] => {
  const mod = readyModule;
  if (!mod) return [];
  const gray = toGrayscale(image);
  const ptr = mod._malloc(gray.byteLength);
  if (!ptr) return [];
  let vector;
  try {
    mod.HEAPU8.set(gray, ptr);
    vector = mod.readBarcodesFromPixmap(ptr, image.width, image.height, ENCODED_OPTIONS);
  } finally {
    mod._free(ptr);
  }
  const out: RawSymbol[] = [];
  for (let i = 0; i < vector.size(); i++) {
    const result = vector.get(i);
    if (!result || !result.isValid || !result.text) continue;
    const p = result.position;
    out.push({
      text: result.text,
      corners: {
        topLeft: { x: p.topLeft.x, y: p.topLeft.y },
        topRight: { x: p.topRight.x, y: p.topRight.y },
        bottomRight: { x: p.bottomRight.x, y: p.bottomRight.y },
        bottomLeft: { x: p.bottomLeft.x, y: p.bottomLeft.y },
      },
    });
  }
  return out;
};
