// =====================================================
// Vendor the zxing-cpp reader wasm INTO the source tree, as base64
// =====================================================
// The CONSUME contract is self-contained: nothing is fetched at runtime, from
// anywhere, including the app's own origin. WebAssembly is not forbidden;
// *fetching* is. `zxing-wasm`'s published `locateFile` points at
// fastly.jsdelivr.net and its build emits `zxing_reader.wasm` as a separate
// asset, so neither the package default nor an ordinary Vite asset import
// satisfies the contract.
//
// This writes the binary into `vendor/zxingReaderWasm.ts` as a base64 string
// literal. The bundler then treats it as source: one file reaches the browser,
// compressed by the same path as the JS, and `WebAssembly` is handed the bytes
// directly with no `fetch` of any kind — not even of a `data:` URI.
//
//   node scripts/vendor-zxing.mjs
//
// Re-run it after any change to the pinned `zxing-wasm` version. The generated
// file records the version and the SHA-256 it was cut from, and
// `tests/qr-decoder-tests.mjs` fails if the two disagree with what is installed.
// =====================================================

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '..');

const pkg = JSON.parse(readFileSync(join(REPO, 'node_modules', 'zxing-wasm', 'package.json'), 'utf8'));
const wasmPath = join(REPO, 'node_modules', 'zxing-wasm', 'dist', 'reader', 'zxing_reader.wasm');
const bytes = readFileSync(wasmPath);
const sha256 = createHash('sha256').update(bytes).digest('hex');
const base64 = bytes.toString('base64');

const outDir = join(REPO, 'vendor');
mkdirSync(outDir, { recursive: true });
const outFile = join(outDir, 'zxingReaderWasm.ts');

// Wrapped, so the file is diffable and no editor has to hold one 1.4 MB line.
const wrapped = base64.replace(/(.{120})/g, '$1\n').trimEnd();

writeFileSync(outFile,
  `/**
 * GENERATED by scripts/vendor-zxing.mjs — do not edit.
 *
 * The zxing-cpp reader, compiled to WebAssembly, inlined as base64 so that
 * nothing is fetched at runtime. See that script for why this is a source file
 * and not an asset.
 */
export const ZXING_READER_WASM_VERSION = ${JSON.stringify(pkg.version)};
export const ZXING_READER_WASM_SHA256 = ${JSON.stringify(sha256)};
export const ZXING_READER_WASM_BYTES = ${bytes.length};

export const ZXING_READER_WASM_BASE64 =
${wrapped.split('\n').map(l => `  '${l}'`).join(' +\n')};
`);

console.log(`zxing-wasm ${pkg.version}`);
console.log(`  binary   ${bytes.length.toLocaleString()} bytes`);
console.log(`  sha256   ${sha256}`);
console.log(`  base64   ${base64.length.toLocaleString()} chars`);
console.log(`  written  ${outFile}`);
